/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Training Manager API
 * REST API for the Training Manager application
 * OpenAPI spec version: 1.0
 */
import { customFetch } from '../../fetch'
export interface UnauthorizedErrorResponse {
  statusCode: number
  error: string
  message: string
}

export interface ConsistencyDay {
  workoutDayCompleted: boolean
  workoutDayStarted: boolean
}

export interface TodayWorkoutDay {
  workoutPlanId: string
  id: string
  name: string
  isRest: boolean
  weekDay: string
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercisesCount: number
}

export type HomeResponseConsistencyByDay = { [key: string]: ConsistencyDay }

export interface HomeResponse {
  activeWorkoutPlanId: string
  todayWorkoutDay: TodayWorkoutDay | null
  workoutStreak: number
  consistencyByDay: HomeResponseConsistencyByDay
}

export interface NotFoundErrorResponse {
  statusCode: number
  error: string
  message: string
}

/**
 * @nullable
 */
export type GetUserTrainDataOutputDtoWeightInGrams = {
  [key: string]: unknown
} | null

/**
 * @nullable
 */
export type GetUserTrainDataOutputDtoHeightInCentimeters = {
  [key: string]: unknown
} | null

/**
 * @nullable
 */
export type GetUserTrainDataOutputDtoAge = { [key: string]: unknown } | null

/**
 * @nullable
 */
export type GetUserTrainDataOutputDtoBodyFatPercentage = {
  [key: string]: unknown
} | null

export interface GetUserTrainDataOutputDto {
  userId: string
  userName: string
  /** @nullable */
  weightInGrams?: GetUserTrainDataOutputDtoWeightInGrams
  /** @nullable */
  heightInCentimeters?: GetUserTrainDataOutputDtoHeightInCentimeters
  /** @nullable */
  age?: GetUserTrainDataOutputDtoAge
  /** @nullable */
  bodyFatPercentage?: GetUserTrainDataOutputDtoBodyFatPercentage
}

export interface UpsertUserTrainDataInputDto {
  weightInGrams: number
  heightInCentimeters: number
  age: number
  bodyFatPercentage: number
}

export interface UpsertUserTrainDataOutputDto {
  userId: string
  userName: string
  weightInGrams: number
  heightInCentimeters: number
  age: number
  bodyFatPercentage: number
}

export interface ValidationErrorResponse {
  statusCode: number
  error: string
  message: string
}

export interface ExerciseInputDto {
  /** @minimum 0 */
  order: number
  name: string
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /**
   * Tempo de descanso em segundos
   * @minimum 1
   */
  restTimeInSeconds: number
}

export type WorkoutDayInputDtoWeekDay =
  (typeof WorkoutDayInputDtoWeekDay)[keyof typeof WorkoutDayInputDtoWeekDay]

export const WorkoutDayInputDtoWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY'
} as const

export interface WorkoutDayInputDto {
  name: string
  weekDay: WorkoutDayInputDtoWeekDay
  isRest: boolean
  /**
   * Duração estimada em segundos
   * @minimum 1
   */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: ExerciseInputDto[]
}

export interface CreateWorkoutPlanInputDto {
  name: string
  workoutDays: WorkoutDayInputDto[]
}

export interface CreateWorkoutPlanOutputDto {
  id: string
}

export type WorkoutDayOutputDtoWeekDay =
  (typeof WorkoutDayOutputDtoWeekDay)[keyof typeof WorkoutDayOutputDtoWeekDay]

export const WorkoutDayOutputDtoWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY'
} as const

/**
 * @nullable
 */
export type WorkoutDayOutputDtoCoverImageUrl = { [key: string]: unknown } | null

export interface WorkoutDayOutputDto {
  id: string
  name: string
  weekDay: WorkoutDayOutputDtoWeekDay
  isRest: boolean
  /**
   * Duração estimada em segundos
   * @minimum 1
   */
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: WorkoutDayOutputDtoCoverImageUrl
  exerciseCount: number
}

export interface GetWorkoutPlanOutputDto {
  id: string
  name: string
  isActive: boolean
  workoutDays: WorkoutDayOutputDto[]
}

export interface WorkoutDayExerciseOutputDto {
  id: string
  name: string
  /** @minimum 0 */
  order: number
  workoutDayId: string
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /**
   * Tempo de descanso em segundos
   * @minimum 1
   */
  restTimeInSeconds: number
}

export interface WorkoutDaySessionOutputDto {
  id: string
  workoutDayId: string
  startedAt: string
  completedAt?: string
}

/**
 * @nullable
 */
export type GetWorkoutDayOutputDtoCoverImageUrl = {
  [key: string]: unknown
} | null

export type GetWorkoutDayOutputDtoWeekDay =
  (typeof GetWorkoutDayOutputDtoWeekDay)[keyof typeof GetWorkoutDayOutputDtoWeekDay]

export const GetWorkoutDayOutputDtoWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY'
} as const

export interface GetWorkoutDayOutputDto {
  id: string
  name: string
  isRest: boolean
  /** @nullable */
  coverImageUrl?: GetWorkoutDayOutputDtoCoverImageUrl
  /**
   * Duração estimada em segundos
   * @minimum 1
   */
  estimatedDurationInSeconds: number
  weekDay: GetWorkoutDayOutputDtoWeekDay
  exercises: WorkoutDayExerciseOutputDto[]
  sessions: WorkoutDaySessionOutputDto[]
}

export interface ForbiddenErrorResponse {
  statusCode: number
  error: string
  message: string
}

export interface RemoveWorkoutPlanOutputDto {
  id: string
}

export interface StartWorkoutSessionResponse {
  userWorkoutSessionId: string
}

export interface ConflictErrorResponse {
  statusCode: number
  error: string
  message: string
}

export interface CompleteWorkoutSessionBodyDto {
  /** Data/hora de conclusão da sessão (ISO 8601) */
  completedAt: string
}

export interface CompleteWorkoutSessionResponse {
  id: string
  completedAt: string
  startedAt: string
}

export type GetStatsOutputDtoConsistencyByDay = {
  [key: string]: ConsistencyDay
}

export interface GetStatsOutputDto {
  workoutStreak: number
  consistencyByDay: GetStatsOutputDtoConsistencyByDay
  completedWorkoutsCount: number
  conclusionRate: number
  totalTimeInSeconds: number
}

/**
 * Quem enviou a mensagem
 */
export type AssistantMessageDtoRole =
  (typeof AssistantMessageDtoRole)[keyof typeof AssistantMessageDtoRole]

export const AssistantMessageDtoRole = {
  user: 'user',
  assistant: 'assistant',
  system: 'system'
} as const

export interface AssistantMessageDto {
  /** ID único da mensagem */
  id: string
  /** Quem enviou a mensagem */
  role: AssistantMessageDtoRole
  /** Array de partes da mensagem (formato useChat do Vercel AI SDK) */
  parts: string[]
}

export interface AssistantBodyDto {
  /** Histórico de mensagens da conversa. Formato useChat do Vercel AI SDK. */
  messages: AssistantMessageDto[]
}

export type GetHomeDataParams = {
  /**
   * Offset do fuso horário em minutos (ex: -180 = UTC-3)
   */
  timezoneOffset?: number
}

export type ListWorkoutPlansParams = {
  /**
   * Filter by active status
   */
  active?: ListWorkoutPlansActive
}

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive]

export const ListWorkoutPlansActive = {
  true: 'true',
  false: 'false'
} as const

export type GetStatsParams = {
  from: string
  to: string
  timezoneOffset?: number
}

/**
 * Check if the server is running.
 * @summary Health Check
 */
export type healthCheckResponse200 = {
  data: void
  status: 200
}

export type healthCheckResponseSuccess = healthCheckResponse200 & {
  headers: Headers
}
export type healthCheckResponse = healthCheckResponseSuccess

export const getHealthCheckUrl = () => {
  return `/health-check`
}

export const healthCheck = async (
  options?: RequestInit
): Promise<healthCheckResponse> => {
  return customFetch<healthCheckResponse>(getHealthCheckUrl(), {
    ...options,
    method: 'GET'
  })
}

/**
 * Returns the authenticated user home page data for a given date, including today workout, streak and weekly consistency.
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: HomeResponse
  status: 200
}

export type getHomeDataResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getHomeDataResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers
}
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
) & {
  headers: Headers
}

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError

export const getGetHomeDataUrl = (date: string, params?: GetHomeDataParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/home/${date}?${stringifiedParams}`
    : `/home/${date}`
}

export const getHomeData = async (
  date: string,
  params?: GetHomeDataParams,
  options?: RequestInit
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date, params), {
    ...options,
    method: 'GET'
  })
}

/**
 * Lists all users. Requires admin privileges (user ID in ADMIN_USER_IDS).
 * @summary Get all users (admin)
 */
export type listUsersResponse200 = {
  data: void
  status: 200
}

export type listUsersResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type listUsersResponseSuccess = listUsersResponse200 & {
  headers: Headers
}
export type listUsersResponseError = listUsersResponse401 & {
  headers: Headers
}

export type listUsersResponse =
  | listUsersResponseSuccess
  | listUsersResponseError

export const getListUsersUrl = () => {
  return `/users`
}

export const listUsers = async (
  options?: RequestInit
): Promise<listUsersResponse> => {
  return customFetch<listUsersResponse>(getListUsersUrl(), {
    ...options,
    method: 'GET'
  })
}

/**
 * Returns the authenticated user profile and training data. Fields are null if not yet set.
 * @summary Get authenticated user train data
 */
export type getAuthenticatedUserTrainDataResponse200 = {
  data: GetUserTrainDataOutputDto
  status: 200
}

export type getAuthenticatedUserTrainDataResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getAuthenticatedUserTrainDataResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type getAuthenticatedUserTrainDataResponseSuccess =
  getAuthenticatedUserTrainDataResponse200 & {
    headers: Headers
  }
export type getAuthenticatedUserTrainDataResponseError = (
  | getAuthenticatedUserTrainDataResponse401
  | getAuthenticatedUserTrainDataResponse404
) & {
  headers: Headers
}

export type getAuthenticatedUserTrainDataResponse =
  | getAuthenticatedUserTrainDataResponseSuccess
  | getAuthenticatedUserTrainDataResponseError

export const getGetAuthenticatedUserTrainDataUrl = () => {
  return `/users/me`
}

export const getAuthenticatedUserTrainData = async (
  options?: RequestInit
): Promise<getAuthenticatedUserTrainDataResponse> => {
  return customFetch<getAuthenticatedUserTrainDataResponse>(
    getGetAuthenticatedUserTrainDataUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

/**
 * Creates or updates the training data for the authenticated user.
 * @summary Update authenticated user train data
 */
export type updateAuthenticatedUserTrainDataResponse200 = {
  data: UpsertUserTrainDataOutputDto
  status: 200
}

export type updateAuthenticatedUserTrainDataResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type updateAuthenticatedUserTrainDataResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type updateAuthenticatedUserTrainDataResponseSuccess =
  updateAuthenticatedUserTrainDataResponse200 & {
    headers: Headers
  }
export type updateAuthenticatedUserTrainDataResponseError = (
  | updateAuthenticatedUserTrainDataResponse400
  | updateAuthenticatedUserTrainDataResponse401
) & {
  headers: Headers
}

export type updateAuthenticatedUserTrainDataResponse =
  | updateAuthenticatedUserTrainDataResponseSuccess
  | updateAuthenticatedUserTrainDataResponseError

export const getUpdateAuthenticatedUserTrainDataUrl = () => {
  return `/users/me`
}

export const updateAuthenticatedUserTrainData = async (
  upsertUserTrainDataInputDto: UpsertUserTrainDataInputDto,
  options?: RequestInit
): Promise<updateAuthenticatedUserTrainDataResponse> => {
  return customFetch<updateAuthenticatedUserTrainDataResponse>(
    getUpdateAuthenticatedUserTrainDataUrl(),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(upsertUserTrainDataInputDto)
    }
  )
}

/**
 * Fetches a user by ID. Requires admin privileges (user ID in ADMIN_USER_IDS).
 * @summary Get user by ID (admin)
 */
export type getUserByIdResponse200 = {
  data: void
  status: 200
}

export type getUserByIdResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getUserByIdResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type getUserByIdResponseSuccess = getUserByIdResponse200 & {
  headers: Headers
}
export type getUserByIdResponseError = (
  | getUserByIdResponse401
  | getUserByIdResponse404
) & {
  headers: Headers
}

export type getUserByIdResponse =
  | getUserByIdResponseSuccess
  | getUserByIdResponseError

export const getGetUserByIdUrl = (userId: string) => {
  return `/users/${userId}`
}

export const getUserById = async (
  userId: string,
  options?: RequestInit
): Promise<getUserByIdResponse> => {
  return customFetch<getUserByIdResponse>(getGetUserByIdUrl(userId), {
    ...options,
    method: 'GET'
  })
}

/**
 * Create a new workout plan.
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlanOutputDto
  status: 201
}

export type createWorkoutPlanResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type createWorkoutPlanResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers
}
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
) & {
  headers: Headers
}

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plan`
}

export const createWorkoutPlan = async (
  createWorkoutPlanInputDto: CreateWorkoutPlanInputDto,
  options?: RequestInit
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkoutPlanInputDto)
  })
}

/**
 * List all workout plans. Without query params, returns all plans. Use ?active=true for active only, ?active=false for inactive only.
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: GetWorkoutPlanOutputDto[]
  status: 200
}

export type listWorkoutPlansResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers
}
export type listWorkoutPlansResponseError = listWorkoutPlansResponse401 & {
  headers: Headers
}

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/workout-plan?${stringifiedParams}`
    : `/workout-plan`
}

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: 'GET'
  })
}

/**
 * Get the currently active workout plan for the logged-in user.
 * @summary Get active workout plan
 */
export type getActiveWorkoutPlanResponse200 = {
  data: GetWorkoutPlanOutputDto
  status: 200
}

export type getActiveWorkoutPlanResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getActiveWorkoutPlanResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type getActiveWorkoutPlanResponseSuccess =
  getActiveWorkoutPlanResponse200 & {
    headers: Headers
  }
export type getActiveWorkoutPlanResponseError = (
  | getActiveWorkoutPlanResponse401
  | getActiveWorkoutPlanResponse404
) & {
  headers: Headers
}

export type getActiveWorkoutPlanResponse =
  | getActiveWorkoutPlanResponseSuccess
  | getActiveWorkoutPlanResponseError

export const getGetActiveWorkoutPlanUrl = () => {
  return `/workout-plan/active`
}

export const getActiveWorkoutPlan = async (
  options?: RequestInit
): Promise<getActiveWorkoutPlanResponse> => {
  return customFetch<getActiveWorkoutPlanResponse>(
    getGetActiveWorkoutPlanUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

/**
 * Get a specific workout day with its exercises and sessions.
 * @summary Get workout day details
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDayOutputDto
  status: 200
}

export type getWorkoutDayResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getWorkoutDayResponse403 = {
  data: ForbiddenErrorResponse
  status: 403
}

export type getWorkoutDayResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers
}
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse403
  | getWorkoutDayResponse404
) & {
  headers: Headers
}

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError

export const getGetWorkoutDayUrl = (planId: string, dayId: string) => {
  return `/workout-plan/${planId}/days/${dayId}`
}

export const getWorkoutDay = async (
  planId: string,
  dayId: string,
  options?: RequestInit
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(planId, dayId),
    {
      ...options,
      method: 'GET'
    }
  )
}

/**
 * Remove a workout plan by its ID.
 * @summary Remove a workout plan
 */
export type removeWorkoutPlanResponse200 = {
  data: RemoveWorkoutPlanOutputDto
  status: 200
}

export type removeWorkoutPlanResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type removeWorkoutPlanResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type removeWorkoutPlanResponseSuccess = removeWorkoutPlanResponse200 & {
  headers: Headers
}
export type removeWorkoutPlanResponseError = (
  | removeWorkoutPlanResponse401
  | removeWorkoutPlanResponse404
) & {
  headers: Headers
}

export type removeWorkoutPlanResponse =
  | removeWorkoutPlanResponseSuccess
  | removeWorkoutPlanResponseError

export const getRemoveWorkoutPlanUrl = (id: string) => {
  return `/workout-plan/${id}`
}

export const removeWorkoutPlan = async (
  id: string,
  options?: RequestInit
): Promise<removeWorkoutPlanResponse> => {
  return customFetch<removeWorkoutPlanResponse>(getRemoveWorkoutPlanUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

/**
 * Start a workout session for a specific day of a workout plan.
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSessionResponse
  status: 201
}

export type startWorkoutSessionResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type startWorkoutSessionResponse403 = {
  data: ForbiddenErrorResponse
  status: 403
}

export type startWorkoutSessionResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type startWorkoutSessionResponse409 = {
  data: ConflictErrorResponse
  status: 409
}

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers
  }
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse403
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
) & {
  headers: Headers
}

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError

export const getStartWorkoutSessionUrl = (planId: string, dayId: string) => {
  return `/workout-plan/${planId}/days/${dayId}/sessions`
}

export const startWorkoutSession = async (
  planId: string,
  dayId: string,
  options?: RequestInit
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(planId, dayId),
    {
      ...options,
      method: 'POST'
    }
  )
}

/**
 * Complete a specific workout session by setting completedAt.
 * @summary Complete a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSessionResponse
  status: 200
}

export type completeWorkoutSessionResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type completeWorkoutSessionResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type completeWorkoutSessionResponse403 = {
  data: ForbiddenErrorResponse
  status: 403
}

export type completeWorkoutSessionResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers
  }
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse400
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse403
  | completeWorkoutSessionResponse404
) & {
  headers: Headers
}

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseSuccess
  | completeWorkoutSessionResponseError

export const getCompleteWorkoutSessionUrl = (
  planId: string,
  dayId: string,
  sessionId: string
) => {
  return `/workout-plan/${planId}/days/${dayId}/sessions/${sessionId}`
}

export const completeWorkoutSession = async (
  planId: string,
  dayId: string,
  sessionId: string,
  completeWorkoutSessionBodyDto: CompleteWorkoutSessionBodyDto,
  options?: RequestInit
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(planId, dayId, sessionId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(completeWorkoutSessionBodyDto)
    }
  )
}

/**
 * Returns stats for the authenticated user within a date range, including workout streak, consistency, completion rate and total time.
 * @summary Get user stats
 */
export type getStatsResponse200 = {
  data: GetStatsOutputDto
  status: 200
}

export type getStatsResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers
}
export type getStatsResponseError = getStatsResponse401 & {
  headers: Headers
}

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/stats?${stringifiedParams}` : `/stats`
}

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: 'GET'
  })
}

/**
 * AI Assistant.
 * @summary AI Assistant
 */
export type chatWithAssistantResponse200 = {
  data: void
  status: 200
}

export type chatWithAssistantResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type chatWithAssistantResponseSuccess = chatWithAssistantResponse200 & {
  headers: Headers
}
export type chatWithAssistantResponseError = chatWithAssistantResponse401 & {
  headers: Headers
}

export type chatWithAssistantResponse =
  | chatWithAssistantResponseSuccess
  | chatWithAssistantResponseError

export const getChatWithAssistantUrl = () => {
  return `/ai`
}

export const chatWithAssistant = async (
  assistantBodyDto: AssistantBodyDto,
  options?: RequestInit
): Promise<chatWithAssistantResponse> => {
  return customFetch<chatWithAssistantResponse>(getChatWithAssistantUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(assistantBodyDto)
  })
}
